import pandas as pd
brands_data = [
    {"name": "Microsoft", "description": "Global technology giant specializing in cloud computing, enterprise software, operating systems, and productivity suites."},
    {"name": "Apple", "description": "Premium consumer electronics company focusing on smartphones, personal computers, tablets, wearables, and ecosystem software."},
    {"name": "Google", "description": "Alphabet subsidiary dominating web search, cloud infrastructure, online advertising, mobile operating systems, and artificial intelligence models."},
    {"name": "Amazon AWS", "description": "On-demand cloud computing platforms and APIs providing distributed storage, compute power, and machine learning tools for enterprises."},
    {"name": "Meta", "description": "Social technology conglomerate operating global networking platforms, instant messaging apps, virtual reality hardware, and digital ad systems."},
    {"name": "Salesforce", "description": "Cloud-based customer relationship management (CRM) platform providing enterprise software for sales, service, and marketing automation."},
    {"name": "Adobe", "description": "Creative software enterprise providing digital media creation, multimedia editing tools, vector graphics, and document management cloud services."},
    {"name": "OpenAI", "description": "Artificial intelligence research and deployment company developing cutting-edge large language models, generative tools, and safety frameworks."},
    {"name": "Infosys", "description": "Indian multinational information technology company providing business consulting, software engineering, and next-generation digital services."},
    {"name": "TCS", "description": "Tata Consultancy Services, a leading global IT services, consulting, and business solutions organization with massive enterprise presence."},
    {"name": "Wipro", "description": "Global information technology, consulting, and business process services company driving digital transformation and cognitive computing."},
    {"name": "HCLTech", "description": "Next-generation global technology company helping enterprises reimagine their businesses for the digital age with cloud and engineering solutions."},
    {"name": "Oracle", "description": "Enterprise software corporation specializing in database management systems, cloud engineered systems, and enterprise resource planning (ERP) software."},
    {"name": "SAP", "description": "Multinational software corporation developing enterprise software to manage business operations, logistics, finances, and customer relations."},
    {"name": "IBM", "description": "Technology and consulting corporation focusing on global hybrid cloud infrastructure, cognitive computing, mainframe hardware, and quantum research."},
    {"name": "Nvidia", "description": "Pioneering technology company designing graphics processing units (GPUs) for gaming, professional visualization, and high-performance AI computing."},
    {"name": "Intel", "description": "Semiconductor giant designing and manufacturing microprocessors, chipsets, and computing hardware components for global supply chains."},
    {"name": "AMD", "description": "Semiconductor company developing computer processors, high-performance graphics engines, and adaptive computing technologies for data centers."},
    {"name": "Cisco", "description": "Global networking hardware and software provider specializing in routers, switches, cybersecurity solutions, and cloud communication infrastructure."},
    {"name": "Zoom", "description": "Cloud-based video communications platform providing videotelephony, online chat, business webinars, and collaborative workspace solutions."},
    {"name": "Slack", "description": "Enterprise productivity messaging platform centralizing corporate communication, file sharing, and automated app integrations."},
    {"name": "Atlassian", "description": "Software company developing collaborative project tracking, issue management, agile development, and content management tools like Jira."},
    {"name": "GitHub", "description": "Cloud-based hosting service for version control and software collaboration utilizing git, featuring code sharing and CI/CD tools."},
    {"name": "GitLab", "description": "Comprehensive DevOps platform providing a single application for the entire software development lifecycle, security, and hosting."},
    {"name": "Datadog", "description": "Monitoring and security platform for cloud-scale applications, providing full-stack observability, metrics, and log management."},
    {"name": "Snowflake", "description": "Cloud-based data warehousing and analytics platform enabling seamless data storage, processing, and analytic solutions."},
    {"name": "Palantir", "description": "Analytical software company specializing in big data analytics integration platforms for government agencies and financial institutions."},
    {"name": "Canva", "description": "Graphic design platform used to create social media graphics, presentations, posters, documents, and visual digital content easily."},
    {"name": "Figma", "description": "Collaborative web-based interface design tool used for UI/UX prototyping, vector graphics creation, and design system management."},
    {"name": "Shopify", "description": "Global e-commerce platform enabling merchants to build online stores, manage retail points of sale, and scale payment gateways."},
    {"name": "Squarespace", "description": "Website building and hosting platform providing SaaS for website creation, blogging tools, and e-commerce store configurations."},
    {"name": "Wix", "description": "Cloud-based web development platform allowing users to create HTML5 websites and mobile sites through online drag-and-drop tools."},
    {"name": "WordPress", "description": "Open-source content management system powering a massive percentage of global websites, blogs, and customized e-commerce stores."},
    {"name": "HubSpot", "description": "Inbound marketing, sales, and customer service SaaS platform providing software tools for social media marketing and content management."},
    {"name": "Twilio", "description": "Cloud communications platform as a service enabling developers to programmatically make phone calls, send text messages, and web chat."},
    {"name": "Stripe", "description": "Financial infrastructure platform providing payment processing software and application programming interfaces for internet businesses."},
    {"name": "PayPal", "description": "Global digital payments processing company operating a worldwide online payments system supporting electronic money transfers."},
    {"name": "Square", "description": "Block subsidiary providing financial services, mobile merchant payment processing aggregators, and small business hardware solutions."},
    {"name": "Adyen", "description": "Global payment company allowing businesses to accept e-commerce, mobile, and point-of-sale payments across unified global channels."},
    {"name": "Coinbase", "description": "Digital currency exchange platform providing infrastructure for trading, investing, storing, and utilizing cryptographic assets."},
    {"name": "Binance", "description": "Global cryptocurrency platform providing exchange ecosystems, blockchain infrastructure, digital wallets, and decentralized finance networks."},
    {"name": "Asana", "description": "Web and mobile application designed to help teams organize, track, manage, and optimize their daily corporate workflows."},
    {"name": "Monday.com", "description": "Cloud-based work operating system where teams can create custom workflow applications to run projects, processes, and tasks."},
    {"name": "Notion", "description": "All-in-one collaborative workspace application for note-taking, knowledge management, databases, project tracking, and documentation."},
    {"name": "Trello", "description": "Visual team collaboration tool utilizing Kanban boards, lists, and cards to organize projects and prioritize tasks flexibly."},
    {"name": "Amazon Retail", "description": "Global e-commerce marketplace dominating online retail, consumer logistics, third-party merchant hosting, and prime delivery services."},
    {"name": "Walmart", "description": "Multinational retail corporation operating a massive global chain of hypermarkets, discount department stores, and grocery outlets."},
    {"name": "Flipkart", "description": "Major Indian e-commerce marketplace competing across consumer electronics, fashion apparel, home essentials, and grocery delivery networks."},
    {"name": "Myntra", "description": "Premium Indian fashion and lifestyle e-commerce platform showcasing domestic and international apparel brands, cosmetics, and accessories."},
    {"name": "Nykaa", "description": "Indian lifestyle retail platform specializing in beauty, wellness, cosmetics, luxury skincare, and curated fashion apparel stores."},
    {"name": "Ajio", "description": "Reliance Retail digital fashion marketplace offering handpicked trendy western apparel, traditional ethnic wear, and luxury global brands."},
    {"name": "Tata CliQ", "description": "Omnichannel e-commerce platform offering premium multi-brand fashion retail, luxury accessories, and consumer electronics."},
    {"name": "eBay", "description": "Global e-commerce platform facilitating consumer-to-consumer and business-to-consumer sales through auction-style trading and instant purchasing."},
    {"name": "Alibaba", "description": "Global wholesale trade platform connecting international manufacturers with worldwide business buyers and massive supply chains."},
    {"name": "AliExpress", "description": "Online retail service made up of small businesses offering affordable consumer products to international online buyers."},
    {"name": "Target", "description": "Large-scale general merchandise discount retailer providing everyday consumer goods, home decor, clothing, and grocery options."},
    {"name": "Costco", "description": "Membership-only wholesale warehouse club providing bulk grocery items, consumer electronics, apparel, and hardware supplies."},
    {"name": "Nike", "description": "Global athletic footwear, performance sportswear, active apparel, equipment, and sports lifestyle accessory designer and manufacturer."},
    {"name": "Adidas", "description": "Multinational corporation designing and manufacturing athletic shoes, sportswear, causal apparel, and sporting gear."},
    {"name": "Puma", "description": "Global sports brand designing, developing, and selling casual and athletic footwear, apparel, and performance running gear."},
    {"name": "Under Armour", "description": "Performance athletic apparel brand specializing in branded sportswear, casual footwear, and moisture-wicking athletic gear."},
    {"name": "Zara", "description": "Inditex subsidiary dominating fast-fashion apparel retail with highly responsive production, global trend translation, and modern stores."},
    {"name": "H&M", "description": "Multinational clothing retail company known for its fast-fashion clothing options for men, women, teenagers, and children."},
    {"name": "Uniqlo", "description": "Japanese casual wear designer and retailer focusing on minimalist high-quality basics, innovative fabric tech, and functional apparel."},
    {"name": "ASOS", "description": "Global online fashion and cosmetic retailer aimed primarily at young adults, offering multi-brand clothes and beauty products."},
    {"name": "Shein", "description": "Ultra-fast-fashion digital marketplace leveraging algorithm-driven supply chains to retail extremely affordable clothing items globally."},
    {"name": "Louis Vuitton", "description": "Iconic French luxury fashion house manufacturing high-end leather goods, monogram handbags, trunk luggage, ready-to-wear apparel, and luxury accessories."},
    {"name": "Gucci", "description": "High-end Italian luxury fashion brand specializing in premium leather accessories, designer clothing, footwear, and luxury lifestyle products."},
    {"name": "Chanel", "description": "Private French luxury brand focusing on high fashion, ready-to-wear designer clothes, luxury goods, fragrances, and fine jewelry."},
    {"name": "Hermes", "description": "Ultra-luxury French manufacturer specializing in handmade leather goods, iconic Birkin handbags, silk scarves, and luxury lifestyle items."},
    {"name": "Prada", "description": "Italian luxury fashion house specializing in leather handbags, travel accessories, designer footwear, ready-to-wear clothing, and runway fashion."},
    {"name": "Rolex", "description": "Iconic luxury watch manufacturer known for precision chronometers, prestigious horology engineering, and high-value timepieces."},
    {"name": "Sephora", "description": "Global personal care and beauty retail chain featuring thousands of cosmetics, skincare, body lotions, and hair styling products."},
    {"name": "LVMH", "description": "Luxury goods conglomerate controlling premier institutions across wines, fashion apparel, leather accessories, perfumes, and high-end cosmetics."},
    {"name": "FabIndia", "description": "Indian retail chain sourcing traditional handloom fabrics and artisanal ethnic wear, organic foods, and handcrafted home furnishings."},
    {"name": "Sabyasachi", "description": "Ultra-premium Indian luxury bridal couture designer house globally renowned for intricate traditional Indian embroidery, handloom lehengas, and heritage jewelry."},
    {"name": "Manyavar", "description": "Vedant Fashions retail network leading the traditional Indian celebratory ethnic wear market for men and women, featuring sherwanis and lehengas."},
    {"name": "Reliance Trends", "description": "Mass-market apparel retail chain offering affordable everyday casual wear, formal attire, and western fashion concepts across India."},
    {"name": "Pantaloons", "description": "Aditya Birla Group multi-brand family fashion retail store network showcasing casual, formal, and ethnic apparel trends."},
    {"name": "Shoppers Stop", "description": "Premier Indian department store chain retailing premium cosmetics, domestic clothing brands, luxury accessories, and home goods."},
    {"name": "Lifestyle Stores", "description": "Large-format department store chain bringing together leading international and national fashion apparel, footwear, and handbag brands."},
    {"name": "Decathlon", "description": "Massive French sporting goods retailer designing and selling hyper-affordable gear, athletic apparel, and outdoor equipment for 80+ sports."},
    {"name": "IKEA", "description": "Global home furnishings retail giant famous for ready-to-assemble minimalist furniture, kitchen appliances, and flat-pack home accessories."},
    {"name": "Wayfair", "description": "E-commerce platform focused entirely on home furnishings, decor, kitchen appliances, furniture sets, and outdoor patio goods."},
    {"name": "Carrefour", "description": "Multinational hypermarket and retail group operating extensive grocery stores, cash-and-carry wholesale warehouses, and convenience marts."},
    {"name": "McDonalds", "description": "World's largest quick-service restaurant chain famous for hamburgers, fast-food franchises, automated drive-thrus, and standardized logistics."},
    {"name": "Starbucks", "description": "Global coffeehouse chain and roastery reserve serving premium specialty coffee espresso drinks, snacks, and branded mugs."},
    {"name": "Subway", "description": "Fast-food franchise specializing in customizable submarine sandwiches, fresh salads, and health-focused quick-service options."},
    {"name": "KFC", "description": "Yum! Brands subsidiary specializing in southern fried chicken buckets, fast-food franchises, and quick-service meals globally."},
    {"name": "Pizza Hut", "description": "Global pizza restaurant franchise offering signature deep-dish pizzas, pasta side items, and quick residential delivery options."},
    {"name": "Dominos", "description": "Global pizza delivery giant utilizing advanced logistics, mobile ordering tech, and fast distribution fulfillment networks."},
    {"name": "Burger King", "description": "Fast-food hamburger chain famous for flame-broiled burgers, competitive quick-service franchises, and global value menus."},
    {"name": "Coca-Cola", "description": "Global beverage corporation manufacturing concentrate syrups for carbonated soft drinks, juices, bottled water brands, and energy drinks."},
    {"name": "PepsiCo", "description": "Food and beverage conglomerate managing massive portfolio brands across soft drinks, Frito-Lay snacks, Quaker oats, and sports energy beverages."},
    {"name": "Nestle", "description": "Massive global food and drink processing conglomerate producing baby food, bottled water, breakfast cereals, coffee, dairy, and confectionery products."},
    {"name": "Unilever", "description": "Consumer goods giant manufacturing massive portfolios across packaged foods, ice creams, household cleaning agents, and personal care cosmetics."},
    {"name": "ITC Food", "description": "Major Indian conglomerate food division managing popular consumer packaged goods brands across staples, snacks, biscuits, and confectionery."},
    {"name": "Amul", "description": "Indian dairy cooperative society processing milk, butter, cheese, ice cream, and dairy alternatives with a massive nationwide supply network."},
    {"name": "Britannia", "description": "Leading Indian food company specializing in manufacturing premium biscuits, bakery breads, cakes, dairy goods, and snack rusks."},
    {"name": "Haldirams", "description": "Indian sweets, traditional savory snacks, and fast-casual restaurant chain operating nationwide packaged food distribution models."},
    {"name": "Zomato", "description": "Indian food delivery aggregator, hyper-local search engine, and restaurant review platform expanding into quick-commerce grocery apps."},
    {"name": "Swiggy", "description": "On-demand hyper-local delivery platform matching users with local restaurants, instant grocery networks, and parcel pickup services."},
    {"name": "Uber Eats", "description": "Global online food ordering and delivery platform leveraging independent gig-economy courier drivers to service restaurants."},
    {"name": "DoorDash", "description": "Leading food delivery app connecting consumers with local restaurants, convenience stores, and pet supply retailers across suburban landscapes."},
    {"name": "Grubhub", "description": "Online and mobile food ordering and delivery marketplace connecting diners with local takeout restaurants in major urban hubs."},
    {"name": "Chipotle", "description": "Fast-casual restaurant chain specializing in responsibly sourced burritos, tacos, bowls, and fresh Mexican-style ingredients."},
    {"name": "Dunkin", "description": "Quick-service restaurant chain focusing on baked goods, morning breakfast sandwiches, and high-volume drip coffee sales."},
    {"name": "Taco Bell", "description": "Fast-food restaurant franchise providing craveable Mexican-inspired menu items like tacos, quesadillas, and commercial value boxes."},
    {"name": "Kelloggs", "description": "Multinational food company manufacturing ready-to-eat breakfast cereals, toaster pastries, and wholesome snack crackers globally."},
    {"name": "Danone", "description": "Fresh dairy products enterprise focusing on health-oriented yogurts, plant-based nutritional milks, specialized medical foods, and bottled waters."},
    {"name": "Mondelez", "description": "Global confectionery power manufacturer managing premier chocolate brands, biscuits, cookies, and powdered beverage mixes."},
    {"name": "Mars Inc", "description": "Private global pet care and confectionery manufacturer producing leading candy bars, chewing gums, and high-volume pet food brands."},
    {"name": "Hersheys", "description": "Major North American chocolate manufacturer producing iconic baking ingredients, chocolate bars, syrups, and sweet treats."},
    {"name": "Red Bull", "description": "Premium functional energy drink brand dominating extreme sports sponsorships, athlete marketing networks, and beverage manufacturing."},
    {"name": "Monster Energy", "description": "High-volume lifestyle energy beverage brand distributing specialized energy formulations, juice lines, and natural brewing variants."},
    {"name": "Heineken", "description": "Premium global brewing company producing recognized lager brands, alternative hard ciders, and non-alcoholic beer variants."},
    {"name": "Anheuser-Busch", "description": "Massive global brewing enterprise managing vast portfolios of standard beer brands, seltzers, and distribution logistics networks."},
    {"name": "Dabur", "description": "Indian consumer goods enterprise producing natural Ayurvedic healthcare products, personal care items, and pure fruit juices."},
    {"name": "Marico", "description": "Leading consumer products company specializing in health, beauty, premium edible oils, and coconut-based hair care products."},
    {"name": "Godrej Consumer", "description": "Emerging markets consumer goods enterprise focused on home insecticides, hair colorants, soaps, and air freshener lines."},
    {"name": "Tata Consumer", "description": "Integrated food and beverage company distribution network focusing on packaged teas, coffees, mineral waters, salts, and pulses."},
    {"name": "Mother Dairy", "description": "National dairy company marketing milk, ice creams, cultured dairy products, and frozen fruits under advanced processing cooperatives."},
    {"name": "Bikanervala", "description": "Traditional Indian sweet manufacturer and restaurant chain delivering traditional authentic snacks, packaging lines, and quick meals."},
    {"name": "Star Bazaar", "description": "Tata-backed hypermarket chain offering expansive fresh produce sections, general staple groceries, and everyday household necessities."},
    {"name": "BigBasket", "description": "Indian online grocery market service delivering fresh produce, pantry goods, kitchen staples, and rapid home essentials."},
    {"name": "Visa", "description": "Global payments technology network facilitating fast digital funds transfers, authorization clearing, and credit/debit card infrastructure."},
    {"name": "Mastercard", "description": "Multinational financial services corporation processing secure merchant payment transactions and issuing consumer credit line access."},
    {"name": "American Express", "description": "Premium financial institution issuing charge cards, processing travel service payments, and managing global institutional credit lines."},
    {"name": "JPMorgan Chase", "description": "Global investment bank and financial services holding company managing consumer retail banking, corporate assets, and private wealth wealth management."},
    {"name": "Goldman Sachs", "description": "Leading global investment banking, securities management, and investment management firm advising corporate institutions."},
    {"name": "Morgan Stanley", "description": "Global financial services firm advising clients on wealth management, investment banking strategies, and institutional trading fields."},
    {"name": "HSBC", "description": "Multinational banking and financial services organization managing international wealth, corporate accounts, and commercial investment retail portals."},
    {"name": "Citi", "description": "Global financial services corporation providing consumer credit cards, retail banking lines, and enterprise cash management services."},
    {"name": "Bank of America", "description": "Massive consumer retail banking institution offering personal checking, corporate financing, and investment management services."},
    {"name": "SBI", "description": "State Bank of India, the largest public sector banking and financial services statutory body across the Indian subcontinent."},
    {"name": "HDFC Bank", "description": "India's largest private sector bank providing personal banking loans, credit lines, wholesale banking services, and digital accounts."},
    {"name": "ICICI Bank", "description": "Leading private sector Indian bank offering retail loan options, corporate financing accounts, life insurance products, and venture capital."},
    {"name": "Axis Bank", "description": "Major private banking institution providing comprehensive financial services across retail, corporate, and agricultural credit lines in India."},
    {"name": "Paytm", "description": "Indian digital ecosystem company offering mobile wallet infrastructure, QR code merchant payments, utility bills, and micro-loans."},
    {"name": "PhonePe", "description": "Digital payments app built on the Unified Payments Interface (UPI) network facilitating digital recharges and money transfers."},
    {"name": "Google Pay", "description": "Mobile payment wallet platform developed to power contactless smartphone purchases, online checkouts, and peer-to-peer UPI transfers."},
    {"name": "Razorpay", "description": "Indian payment gateway company enabling businesses to accept, process, and disburse digital payments via API developer suites."},
    {"name": "Zerodha", "description": "Indian discount brokerage firm offering retail investment infrastructure for stocks, mutual funds, bonds, and derivatives trading tools."},
    {"name": "Groww", "description": "Digital investment platform allowing retail users to invest in direct mutual funds, domestic stocks, IPOs, and gold options easily."},
    {"name": "Upstox", "description": "Tech-driven online trading platform providing low-cost brokerage options, financial market charts, and retail investment accounts."},
    {"name": "Robinhood", "description": "Financial services app facilitating commission-free stock trading, cryptocurrency investing, and fractional share portfolios via accessible mobile designs."},
    {"name": "Revolut", "description": "Global financial super-app offering multi-currency accounts, instant peer-to-peer money transfers, and digital banking alternatives."},
    {"name": "Wise", "description": "International money transfer platform utilizing local peer networks to bypass standard high-cost cross-border wire processing fees."},
    {"name": "Berkshire Hathaway", "description": "Diversified holding company investing across insurance underwriting, utility networks, freight rail transit, and equity portfolios."},
    {"name": "BlackRock", "description": "World's largest asset management corporation administering exchange-traded funds (ETFs) via enterprise analytical risk infrastructure."},
    {"name": "Vanguard", "description": "Investment advisor giant pioneering low-cost index mutual funds and retail retirement wealth portfolio management services."},
    {"name": "Fidelity", "description": "Multinational financial services corporation managing brokerage assets, mutual funds, 401k plans, and retail wealth tools."},
    {"name": "Charles Schwab", "description": "Savings and loan holding company providing modern wealth brokerage accounts, asset management, and banking lines for individual investors."},
    {"name": "LIC", "description": "Life Insurance Corporation of India, the dominant state-owned insurance provider managing massive sovereign asset pools and long-term policies."},
    {"name": "Bajaj Finance", "description": "Non-banking financial company (NBFC) specializing in consumer durable loans, micro-lending schemes, and personal lines of credit."},
    {"name": "Muthoot Finance", "description": "India's largest gold loan NBFC providing instant liquidity options backed by physical gold ornament collateral reserves."},
    {"name": "Angel One", "description": "Traditional stock brokerage firm transitioned into a digital app ecosystem offering technical trading charts and advisory services."},
    {"name": "PolicyBazaar", "description": "Indian insurance aggregator platform allowing users to view, compare, and purchase life, health, and auto insurance policies online."},
    {"name": "Cred", "description": "Members-only credit card bill payment app rewarding users with premium brand discounts for maintaining high credit scores."},
    {"name": "KreditBee", "description": "Instant personal loan fintech platform targeting young professionals with rapid underwriting and flexible short-term credit options."},
    {"name": "Tesla", "description": "Electric vehicle manufacturer designing autonomous clean energy cars, grid storage battery systems, and residential solar roof cells."},
    {"name": "Toyota", "description": "Automotive manufacturing giant famous for lean production systems, durable passenger sedans, and hybrid drivetrain innovations."},
    {"name": "Volkswagen", "description": "Massive global automotive group managing volume car lines, premium luxury sports brands, and electric vehicle platforms."},
    {"name": "Ford", "description": "Pioneering automotive enterprise mass-producing commercial pickup trucks, passenger utility vehicles, and electric vehicle fleets."},
    {"name": "General Motors", "description": "Global automotive manufacturer producing diverse vehicle brands, global trucking lines, and autonomous driving tech suites."},
    {"name": "Tata Motors", "description": "Indian automotive manufacturing leader producing passenger vehicles, electric cars, and heavy commercial cargo trucks globally."},
    {"name": "Maruti Suzuki", "description": "India's leading passenger car manufacturer dominating mass-market hatchbacks, family sedans, and compact utility cars."},
    {"name": "Mahindra & Mahindra", "description": "Indian automotive manufacturer renowned for rugged utility SUVs, commercial agricultural tractors, and electric commercial vehicles."},
    {"name": "Hyundai", "description": "Global automotive group developing advanced compact cars, family crossovers, and hydrogen fuel cell transport lines."},
    {"name": "BMW", "description": "Premium luxury automotive manufacturer producing high-performance sports sedans, motorcycles, and upscale electric vehicles."},
    {"name": "Mercedes-Benz", "description": "High-end luxury vehicle brand focused on passenger cars, executive limousines, advanced driver assistance technologies, and formula racing."},
    {"name": "Uber", "description": "Ride-hailing transport network company matching users with independent on-demand taxi drivers and corporate transit lines."},
    {"name": "Ola Cabs", "description": "Indian multi-mobility ride-sharing platform extending into electric two-wheeler scooter manufacturing and hyper-local transit networks."},
    {"name": "Lyft", "description": "Ride-hailing service provider coordinating on-demand urban transport lines, shared bikes, and scooter networks across cities."},
    {"name": "FedEx", "description": "Global courier delivery services corporation utilizing dedicated cargo airlines to orchestrate time-sensitive business shipments."},
    {"name": "UPS", "description": "Global package delivery company managing extensive surface truck networks, supply chain logistics, and business freight transit lines."},
    {"name": "DHL", "description": "International express mail services enterprise facilitating air and ocean freight logistics across worldwide customs boundaries."},
    {"name": "Delhivery", "description": "Indian supply chain fulfillment logistics company providing express parcel delivery, warehouse management, and business freight routing software."},
    {"name": "Blue Dart", "description": "Indian express courier delivery services company operating dedicated domestic jet aircraft networks for premium package routing."},
    {"name": "Boeing", "description": "Aerospace manufacturer designing global commercial jetliners, defense defense systems, space launch vehicles, and security tech lines."},
    {"name": "Airbus", "description": "Multinational aerospace corporation designing commercial aircraft carriers, helicopters, and space communication satellites globally."},
    {"name": "Maersk", "description": "Integrated container logistics and shipping giant managing massive oceanic cargo fleets, port terminals, and global intermodal freight routing."},
    {"name": "IndiGo Airlines", "description": "India's largest low-cost passenger airline fleet known for operating punctual, efficient domestic and international flight links."},
    {"name": "Air India", "description": "Tata-owned flag carrier airline operating long-haul international routes and domestic network transit links connecting major cities."},
    {"name": "Emirates", "description": "Premium international airline operator running wide-body global flight links from its central hub infrastructure layouts."},
    {"name": "Indian Railways", "description": "State-operated statutory body administering one of the largest rail transportation networks, cargo freights, and passenger links globally."},
    {"name": "Grab", "description": "Southeast Asian super-app providing ride-hailing services, on-demand food delivery, and digital financial payment transactions across metropolitan hubs."},
    {"name": "Bluedart Express", "description": "South Asian air express courier network managing specialized critical inventory delivery lines and cold-chain healthcare logistics."},
    {"name": "Shiprocket", "description": "E-commerce logistics aggregator platform enabling direct-to-consumer digital brands to negotiate and book multiple shipping carrier options via a single API dashboard."},
    {"name": "Shadowfax", "description": "Hyperlocal on-demand logistics network servicing instant e-commerce order fulfillments, grocery networks, and quick pharmacy distributions."},
    {"name": "Porter", "description": "Intra-city logistics platform enabling users and businesses to book mini-trucks and bike couriers on-demand for moving household goods or cargo."},
    {"name": "Bounce", "description": "Smart mobility startup offering dockless scooter rentals and automated keyless vehicle sharing setups in dense urban grids."},
    {"name": "Rapido", "description": "Indian bike-taxi aggregator and logistics app providing fast, affordable solo commuter transits through congested traffic corridors."},
    {"name": "Rivian", "description": "Electric vehicle manufacturer designing off-road adventure trucks, electric delivery vans, and specialized high-capacity highway battery platforms."},
    {"name": "BYD", "description": "Chinese manufacturing powerhouse specializing in high-volume electric vehicles, battery innovations, mass transit electric buses, and rail networks."}
]
df = pd.DataFrame(brands_data)
df.insert(0, 'id', range(1, len(df) + 1))
df.to_csv("companies.csv", index=False)
print(f" Successfully created a diverse database containing {len(df)} famous brands in 'companies.csv'!")